spring.application.name=focustella-api
spring.config.import=optional:file:./application-local.properties

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5434/focustella}
spring.datasource.username=${DB_USERNAME:focustella}
spring.datasource.password=${DB_PASSWORD:focustella}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=${JWT_SECRET:change-this-secret-key-for-local-development-please-1234567890}
app.jwt.access-token-expiration-seconds=${JWT_ACCESS_TOKEN_EXPIRATION_SECONDS:2592000}
